"""
fit_example_galaxy_galaxy_single_arc.py — SLACS-style single-arc fit driver.

Fits the simulated single-deflector / single-source ring/arc generated by
`Examples/galaxy_galaxy_single_arc/mocks/generate_mock.py`. This is the
canonical "first audited fit" for new lens modelers — Bolton+08 / Auger+10
SLACS setup with one Isothermal+shear deflector + one Sersic source.

    --part direct       Single Nautilus fit of lens light + mass + source.
                        ~12 free params, n_live=150. Wall ≈ 1–2 h on 32 cores.

    --part truth_anchored
                        Same model with tight truth-anchored priors
                        (sigma=0.02 on centres). Used for chi²-at-truth
                        diagnostics + sanity-check baseline.

Usage (Cannon):
    sbatch --time=4:00:00 --mem=64G --cpus-per-task=32 \\
           --job-name=ggsa_direct \\
           --export=ALL,EXAMPLE=galaxy_galaxy_single_arc,FIT_EXTRA_ARGS='--part=direct' \\
           Modules/10_Cluster_Computing/scripts/submit_cannon.slurm

Nautilus auto-resumes from any existing checkpoint.hdf5.
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path


def load_dataset(dataset_root: Path, mask_radius: float = 2.5):
    """Load the single-arc mock + apply a 2.5″ circular mask."""
    import autolens as al

    dataset = al.Imaging.from_fits(
        data_path      = dataset_root / "image.fits",
        noise_map_path = dataset_root / "noise_map.fits",
        psf_path       = dataset_root / "psf.fits",
        pixel_scales   = 0.05,
    )
    mask = al.Mask2D.circular(
        shape_native = dataset.shape_native,
        pixel_scales = dataset.pixel_scales,
        radius       = mask_radius,
    )
    return dataset.apply_mask(mask=mask)


def build_direct_fit(dataset, output_root: Path, n_live: int = 150,
                     tag_suffix: str = ""):
    """Direct fit: lens(Sersic light + Isothermal mass + shear) + source(Sersic).

    Priors are *uninformative* — wide enough that a new modeler sees how
    Nautilus navigates the full search volume. This is the demonstration
    fit for what a 'first lens model' looks like in production.
    """
    import autofit as af
    import autolens as al

    # Lens galaxy at z=0.3 — Sersic light + Isothermal mass + ExternalShear.
    lens_bulge = af.Model(al.lp.Sersic)
    lens_bulge.centre.centre_0 = af.GaussianPrior(mean=0.0, sigma=0.3)
    lens_bulge.centre.centre_1 = af.GaussianPrior(mean=0.0, sigma=0.3)
    lens_bulge.intensity        = af.UniformPrior(lower_limit=0.0, upper_limit=5.0)
    lens_bulge.effective_radius = af.UniformPrior(lower_limit=0.3, upper_limit=3.0)
    lens_bulge.sersic_index     = af.UniformPrior(lower_limit=2.0, upper_limit=6.0)

    lens_mass = af.Model(al.mp.Isothermal)
    lens_mass.centre = lens_bulge.centre  # mass follows light (centre tied)
    lens_mass.einstein_radius = af.UniformPrior(lower_limit=0.5, upper_limit=2.5)

    lens_shear = af.Model(al.mp.ExternalShear)
    lens_shear.gamma_1 = af.GaussianPrior(mean=0.0, sigma=0.05)
    lens_shear.gamma_2 = af.GaussianPrior(mean=0.0, sigma=0.05)

    lens = af.Model(al.Galaxy, redshift=0.3, bulge=lens_bulge,
                    mass=lens_mass, shear=lens_shear)

    # Source galaxy at z=1.0 — Sersic only.
    source_bulge = af.Model(al.lp.Sersic)
    source_bulge.centre.centre_0 = af.GaussianPrior(mean=0.0, sigma=0.3)
    source_bulge.centre.centre_1 = af.GaussianPrior(mean=0.0, sigma=0.3)
    source_bulge.intensity        = af.UniformPrior(lower_limit=0.0, upper_limit=2.0)
    source_bulge.effective_radius = af.UniformPrior(lower_limit=0.05, upper_limit=0.5)
    source_bulge.sersic_index     = af.UniformPrior(lower_limit=0.5, upper_limit=4.0)

    source = af.Model(al.Galaxy, redshift=1.0, bulge=source_bulge)

    model = af.Collection(galaxies=af.Collection(lens=lens, source=source))

    print(f"[GGSA/direct] free params: {model.prior_count}", flush=True)

    analysis = al.AnalysisImaging(dataset=dataset)
    search = af.Nautilus(
        path_prefix=output_root,
        name="ggsa_direct",
        unique_tag=f"ggsa_direct{tag_suffix}",
        n_live=n_live,
        n_batch=50,
        iterations_per_update=5000,
        number_of_cores=int(os.environ.get("SLURM_CPUS_PER_TASK", "1")),
    )
    return search.fit(model=model, analysis=analysis)


def build_truth_anchored_fit(dataset, output_root: Path, n_live: int = 100,
                             tag_suffix: str = ""):
    """Tight-prior truth-anchored fit — chi²-at-truth diagnostic baseline.

    Uses sigma=0.02 on centres and sigma=0.005 on shear components, anchored
    on the mock truth values. Reproduces the chi²-at-truth methodology from
    Modules 11 §3 — gives the noise-floor baseline against which the
    `direct` fit's residuals are compared.
    """
    import autofit as af
    import autolens as al

    lens_bulge = af.Model(al.lp.Sersic)
    lens_bulge.centre.centre_0 = af.GaussianPrior(mean=0.0, sigma=0.02)
    lens_bulge.centre.centre_1 = af.GaussianPrior(mean=0.0, sigma=0.02)
    lens_bulge.intensity        = af.GaussianPrior(mean=1.0, sigma=0.1)
    lens_bulge.effective_radius = af.GaussianPrior(mean=1.0, sigma=0.05)
    lens_bulge.sersic_index     = af.GaussianPrior(mean=4.0, sigma=0.2)

    lens_mass = af.Model(al.mp.Isothermal)
    lens_mass.centre = lens_bulge.centre
    lens_mass.einstein_radius = af.GaussianPrior(mean=1.2, sigma=0.05)

    lens_shear = af.Model(al.mp.ExternalShear)
    lens_shear.gamma_1 = af.GaussianPrior(mean=0.025, sigma=0.005)
    lens_shear.gamma_2 = af.GaussianPrior(mean=-0.015, sigma=0.005)

    lens = af.Model(al.Galaxy, redshift=0.3, bulge=lens_bulge,
                    mass=lens_mass, shear=lens_shear)

    source_bulge = af.Model(al.lp.Sersic)
    source_bulge.centre.centre_0 = af.GaussianPrior(mean=0.12, sigma=0.02)
    source_bulge.centre.centre_1 = af.GaussianPrior(mean=-0.08, sigma=0.02)
    source_bulge.intensity        = af.GaussianPrior(mean=0.35, sigma=0.05)
    source_bulge.effective_radius = af.GaussianPrior(mean=0.15, sigma=0.02)
    source_bulge.sersic_index     = af.GaussianPrior(mean=1.0, sigma=0.1)

    source = af.Model(al.Galaxy, redshift=1.0, bulge=source_bulge)

    model = af.Collection(galaxies=af.Collection(lens=lens, source=source))

    print(f"[GGSA/truth] free params: {model.prior_count}", flush=True)

    analysis = al.AnalysisImaging(dataset=dataset)
    search = af.Nautilus(
        path_prefix=output_root,
        name="ggsa_truth_anchored",
        unique_tag=f"ggsa_truth_anchored{tag_suffix}",
        n_live=n_live,
        n_batch=50,
        iterations_per_update=5000,
        number_of_cores=int(os.environ.get("SLURM_CPUS_PER_TASK", "1")),
    )
    return search.fit(model=model, analysis=analysis)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--part", choices=("direct", "truth_anchored", "all"),
                   default="direct")
    p.add_argument("--output-root", type=Path,
                   default=Path("./output").resolve())
    p.add_argument("--dataset-root", type=Path, required=True,
                   help="Path containing image.fits + noise_map.fits + psf.fits")
    p.add_argument("--repo-root", type=Path, required=False,
                   help="Path to Learning_to_Autolens (slurm-driver compat).")
    p.add_argument("--mask-radius", type=float, default=2.5)
    p.add_argument("--n-live", type=int, default=150)
    args = p.parse_args()

    args.output_root.mkdir(parents=True, exist_ok=True)

    import autolens as al
    print(f"PyAutoLens: {al.__version__}", flush=True)
    print(f"Output root:  {args.output_root}", flush=True)
    print(f"Dataset root: {args.dataset_root}", flush=True)
    print(f"Part:         {args.part}", flush=True)
    print(f"SLURM_JOB_ID: {os.environ.get('SLURM_JOB_ID', '(none)')}",
          flush=True)
    print(f"SLURM_CPUS_PER_TASK: "
          f"{os.environ.get('SLURM_CPUS_PER_TASK', '(none)')}", flush=True)

    t_start = time.time()
    dataset = load_dataset(args.dataset_root, mask_radius=args.mask_radius)
    print(f"Loaded dataset: {dataset.shape_native}, "
          f"{dataset.mask.pixels_in_mask} masked pixels", flush=True)

    if args.part in ("direct", "all"):
        build_direct_fit(dataset, args.output_root, n_live=args.n_live)

    if args.part in ("truth_anchored", "all"):
        build_truth_anchored_fit(dataset, args.output_root, n_live=100)

    print(f"\nTotal wall time: {(time.time()-t_start)/3600:.2f} h", flush=True)


if __name__ == "__main__":
    main()
